plugins {
	id 'java-library'
	id 'maven-publish'
	id 'net.neoforged.gradle.userdev' version '7.1.39'
}

version = mod_version
group = mod_group_id

base {
	archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

repositories {
}

dependencies {
	implementation "net.neoforged:neoforge:${neo_version}"
}

tasks.withType(ProcessResources).configureEach {
	def replaceProperties = [
		minecraft_version: minecraft_version,
		minecraft_version_range: minecraft_version_range,
		neo_version: neo_version,
		mod_id: mod_id,
		mod_name: mod_name,
		mod_license: mod_license,
		mod_version: mod_version,
	]
	inputs.properties(replaceProperties)
	filesMatching(['META-INF/neoforge.mods.toml']) {
		expand(replaceProperties)
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}
