# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.java.home=C:/Users/Tim Wolf/.vscode/extensions/redhat.java-1.56.0-win32-x64/jre/21.0.12.1-win32-x86_64
# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# NeoForge Properties
minecraft_version=1.21.1
neoforge_version=21.1.87

# Mod Properties
version=1.0.1+1.21.1
group=me.avie29.daycounter

