# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.java.home=D:/apps/intellij/jdk/25
# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

minecraft_version=26.3
minecraft_version_range=[26.3]
neo_version=26.3.0.7-beta

# Mod Properties
mod_version=1.0.0+26.3
mod_group_id=me.avie29.daycounter
mod_id=day_counter
mod_name=Day Counter
mod_license=CC-BY-NC-4.0