modLoader="javafml"
loaderVersion="[1,)"
license="${mod_license}"
showAsDataPack=false

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Avie29"
description='''Displays the current Minecraft day in a configurable HUD.'''
displayURL="https://modrinth.com/datapack/avies-day-counter"
logoFile="assets/day-counter/icon.png"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"
